### ISSUE TITLE
Support voor 'Postcode API 2.0'

### ISSUE THREAD

**Issue by nickurt** [nickurt/laravel-postcodeapi#1]
- https://github.com/apiwise/postcodeapi
- https://htmlpreview.github.io/?https://raw.githubusercontent.com/apiwise/postcodeapi/master/docs/index.html

**Comment by akempes** [comment]
I just issued a pull request. I've made a new provider for postcodeapi.nu version 2.0

**Comment by nickurt** [comment]
Thanks!
