### ISSUE TITLE
Add house number addition to address from provider PostcodeApiNu

### ISSUE THREAD

**Issue by tomodutch** [nickurt/laravel-postcodeapi#10]
# Issue
The `nickurt\PostcodeApi\Entity\Address` class that `nickurt\postcodeapi\Providers\nl_NL\PostcodeApiNu` returns does not contain the house number addition.

# Reproduce
Execute the following function:

```php
$provider = \PostcodeApi::create('PostcodeApiNu');
$provider->findByPostcodeAndHouseNumber('4817MK', '148EC6');
```

This will result in:

```php
nickurt\PostcodeApi\Entity\Address {#1136
  #street: null
  #houseNo: null
  #town: null
  #municipality: null
  #province: null
  #latitude: null
  #longitude: null
}
```

The PostcodeApiNu API does include the house number addition as the **addition** field shown in the response from the PostcodeApiNu API:

```json
...
{
 "_embedded": {
    "addresses": [{
			"purpose": "woonfunctie",
			"postcode": "4817MK",
			"addition": "C6",
			"number": 148,
			"year": 1980,
...
```

**Comment by nickurt** [comment]
Should be partly-fixed now, the only problem is that PostcodeAPI is always converting '148EC6' to '148', which makes the responses not always correct ...
