### ISSUE TITLE
Requires PHP 7.2

### ISSUE THREAD

**Issue by J-Brk** [nickurt/laravel-postcodeapi#12]
This packages requires PHP 7.2 minimum, isn't it too high?

**Comment by nickurt** [comment]
By default I support the last 2 versions of PHP, only for this time the package has a higher PHP-requirement than Laravel (which is for 5.8 still on 7.1.3+), but it will be using the same for Laravel 5.9.

If you can't run PHP7.2 in combination with Laravel 5.8 yet, feel free to fork and use that.
