### ISSUE TITLE
Be able to set the http client to be used (unit testing purposes)

### ISSUE THREAD

**Issue by matthijs** [nickurt/laravel-postcodeapi#14]
Hi,

It doesn't seem to be possible to set the http client. I expected to do something like:
```php
$guzzle = new GuzzleHttp\Client();
$postcodeapi = app('PostcodeApi');
$postcodeapi->setHttpClient($guzzle);
```
This way I can mock the responses for the PostcodeApi. Same as you did with the openprovider package for laravel.

Regards, Matthijs

**Comment by nickurt** [comment]
Hi Matthijs, 

It should work on the latest code on the dev-master branch, I will tag an updated version with this later this week ..

```php
$postcodeApi = PostcodeApi::create('PostcodeApiComAu')->setHttpClient(new Client([
    //
]))->find('3306');
```

**Comment by matthijs** [comment]
Hi Nick,

Ah yes, that's also a possibility. The only downside is that I have to adjust the code in my controller instead of just having the http client injected by the unittest.

I'll try your approach.

Regards, Matthijs

**Comment by matthijs** [comment]
Thanks, this approach works for me.
