### ISSUE TITLE
Unable to use provider

### ISSUE THREAD

**Issue by Raymond-Wijkhuizen** [nickurt/laravel-postcodeapi#15]
Hello,

I've gotten this problem when calling functions. When calling functions like this:

$address = \PostcodeApi::create('ApiPostcode')->findByPostcodeAndHouseNumber($request->code, $request->house);

I get the following error:
{message: "Unable to use the provider "ApiPostcode"",…}
exception: "nickurt\PostcodeApi\Exception\InvalidArgumentException"
file: "C:\wamp64\quartzline\vendor\nickurt\laravel-postcodeapi\src\ProviderFactory.php"
line: 18
message: "Unable to use the provider "ApiPostcode""
trace: [{file: "C:\wamp64\quartzline\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php",…},…].

Do you have any ideas to help me out?

Thanks in advance!

**Comment by nickurt** [comment]
It is possible to get this error if you didn't published the config-file,

`php artisan vendor:publish --provider="nickurt\PostcodeApi\ServiceProvider" --tag="config"` 

Contains the `config/postcodeapi.php` file information about `ApiPostcode` ?

You are using v1.9 with Laravel 6.x?
