### ISSUE TITLE
Laravel 5.2 support (Guzzle 6)

### ISSUE THREAD

**Issue by pepijnblom** [nickurt/laravel-postcodeapi#4]
Your package currently does not work with Laravel 5.2 because it Laravel 5.2 uses Guzzle 6.\* and your package requires 5.*

**Comment by destroyer998** [comment]
Please address this issue!

**Comment by tomcoonen** [comment]
@pepijnblom @destroyer998 I've made a quick fork for the Dutch providers at least, will update the rest also and provide a PR here.
Hope it helps you like it did for me.

https://github.com/tomcoonen/laravel-postcodeapi

**Comment by nickurt** [comment]
Thanks tomcoonen, what provider do you want to use destroyer998 ?

**Comment by factormaarten** [comment]
Is dit probleem al opgelost? Ik krijg het namelijk nog niet opgelost.

@tomcoonen Hoe kan ik eventueel jouw fix gebruiken?

**Comment by nickurt** [comment]
@mpjraaij Eigenlijk was ik al vergeten dat dit probleem nog open stond, maar ik zal dit weekend er voor zorgen dat de Nederlandse providers zeker werkend zijn met Laravel 5.3/guzzle6.

**Comment by tomcoonen** [comment]
@mpjraaij werkt hier prima, ik heb nog geen gelegenheid gehad om de rest te updaten.

**Comment by factormaarten** [comment]
Thanks voor de snell reactie beiden. Dan wacht ik even rustig het weekend af.

**Comment by nickurt** [comment]
Ik heb alle providers voorzien van guzzle6/laravel53 support, ik kon alleen postcodenl/pstcd niet 100% verifiëren, zou je de branch dev-guzzle kunnen proberen?

Als alles werkt zal ik het binnenkort mergen/taggen naar master toe ...

**Comment by nickurt** [comment]
@mpjraaij @tomcoonen Ik heb nog wat kleine veranderingen toegevoegd, maar als het goed is zou alles nu prima moeten werken.

**Comment by factormaarten** [comment]
Super thanks @nickurt - Ik ga er deze week weer mee aan de slag.

**Comment by tomcoonen** [comment]
@nickurt Ik ga hem morgen even testen

**Comment by factormaarten** [comment]
Ik heb hem net getest, en waarschijnlijk doe ik zelf nog iets fout, bij:

`$postCode = PostcodeApi::create('PostcodeApiNu2')->find('1118CP');
        var_dump($postCode);`

Krijg ik

> InvalidArgumentException in ProviderFactory.php line 37:
> Unable to use the provider "PostcodeApiNu2"

**Comment by nickurt** [comment]
Ik heb eigenlijk ook PostcodeApiNu2 hernoemd naar PostcodeApiNu (dus even je config-file aanpassen) ...

**Comment by factormaarten** [comment]
@nickurt Thanks! Dat werkt inderdaad een stuk beter. Hij doet het goed nu.

**Comment by nickurt** [comment]
Ik heb de nieuwe versie getagged als 1.0 in de master branch 👍

**Comment by factormaarten** [comment]
Eén klein dingetje nog. Zodra je findByPostcodeAndHouseNumber() gebruikt lijkt hij niet bestaande combinaties niet goed af te vangen. Ik krijg namelijk een ErrorException:

> ErrorException in PostcodeApiNu.php line 68:
> Undefined offset: 0

**Comment by nickurt** [comment]
Hij zou terug moeten komen met een lege Address model als er geen resultaten zijn, met welke postcode/huisnummer krijg je die foutmelding?

**Comment by factormaarten** [comment]
Ik krijg dit met meerdere postcodes die niet bestaan. Bv. 1111XX met huisnummer 425 bestaat niet. Hij geeft echter ook geen lege model.

**Comment by nickurt** [comment]
Hmm, gebruikt je de `nickurt/laravel-postcodeapi:1.*` versie en niet die in dev-guzzle meer? Ik probeerde net 

``` php
PostcodeApi::create('PostcodeApiNu')->findByPostcodeAndHouseNumber('1111XX', '425');
```

en kreeg een leeg model terug ...
