### ISSUE TITLE
wrong url for NationaalGeoRegister

### ISSUE THREAD

**Issue by ixp-nl** [nickurt/laravel-postcodeapi#46]
The url is changed, the correct one is https://api.pdok.nl/bzk/locatieserver/search/v3_1/free
This can be verified by opening the old url in a webbrowser

I've made a patch, but removed the fork before it was patched https://github.com/nickurt/laravel-postcodeapi/pull/45/commits/c773aae9db467e2f561a26d1a908dca1f6b4bfb7

**Comment by nickurt** [comment]
thank you, fixed in 1.19
