### ISSUE TITLE
"Undefined offset: 0"

### ISSUE THREAD

**Issue by bakkertjebrood** [nickurt/laravel-postcodeapi#9]
Laravel 5.5

When I make a call with the following address:

$address = PostcodeApi::create('PostcodeNL')->findByPostcodeAndHouseNumber($request->zipcode, $request->housenumber);

I get this error. Any ideas?
```

{message: "Undefined offset: 0", exception: "ErrorException",…}
exception: "ErrorException"
file: "C:\Projects\nspctr\vendor\guzzlehttp\guzzle\src\Client.php"
line: 348
message: "Undefined offset: 0"
[{file: "C:\Projects\nspctr\vendor\guzzlehttp\guzzle\src\Client.php", line: 348,…},…]
```

**Comment by nickurt** [comment]
It should be working now after my commit to dev-master, could you try it?

**Comment by bakkertjebrood** [comment]
Problem solved! Thx for the quick response and fix!
